/**
 * Customer-facing formatting.
 *
 * The public quote and invoice pages are a stranger's first look at the
 * contractor's professionalism. A raw `5125550142` or an
 * `8/18/2026, 3:44:28 AM` timestamp reads as "generated by software";
 * `(512) 555-0142` and `August 18, 2026` read as prepared by a business.
 */

/** US-style formatting for 10/11-digit numbers; anything else passes through. */
export function formatPhone(raw: string | null | undefined): string {
  if (!raw) return ''
  const digits = raw.replace(/\D/g, '')
  const ten = digits.length === 11 && digits.startsWith('1') ? digits.slice(1) : digits
  if (ten.length !== 10) return raw
  return `(${ten.slice(0, 3)}) ${ten.slice(3, 6)}-${ten.slice(6)}`
}

/** "August 18, 2026" — a date a person would write, no clock time. */
export function formatDateLong(iso: string | null | undefined): string {
  if (!iso) return ''
  const d = new Date(iso)
  if (Number.isNaN(d.getTime())) return ''
  return d.toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })
}

/** "Sep 17" — for compact chips. */
export function formatDateShort(iso: string | null | undefined): string {
  if (!iso) return ''
  const d = new Date(iso)
  if (Number.isNaN(d.getTime())) return ''
  return d.toLocaleDateString('en-US', { month: 'short', day: 'numeric' })
}
