#!/bin/bash

# Supabase OAuth Redirect URL Checker
# This helps verify your configuration

echo "🔍 Checking OAuth Configuration..."
echo ""
echo "Current Environment:"
echo "  NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL:-'Not set'}"
echo ""
echo "URLs to whitelist in Supabase:"
echo "  ✓ http://localhost:3000/auth/callback"
echo "  ✓ http://192.168.0.100:3000/auth/callback"
echo ""
echo "Steps to fix in Supabase Dashboard:"
echo "1. Go to: https://supabase.com/dashboard/project/ajljduisjyutbgjeucig/auth/url-configuration"
echo "2. Under 'Redirect URLs', add BOTH URLs above"
echo "3. Click 'Save'"
echo ""
echo "After updating Supabase:"
echo "1. Clear browser cache/cookies for localhost AND 192.168.0.100"
echo "2. Open browser console (F12) on the login page"
echo "3. Look for console.log showing: 'OAuth redirect will be: ...'"
echo "4. Click 'Continue with Google'"
echo "5. Check that Google redirects to the same IP you're using"
echo ""
echo "If still redirecting to localhost when using 192.168.0.100:"
echo "  - Clear Google account OAuth permissions"
echo "  - Go to: https://myaccount.google.com/permissions"
echo "  - Remove QuoteBuilder Pro app"
echo "  - Try login again"
