#!/bin/bash

echo "════════════════════════════════════════════════════════════"
echo "📱 Mobile Testing with ngrok (Required for Google OAuth)"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "Why ngrok? Google OAuth only accepts:"
echo "  ✅ localhost (Mac only)"
echo "  ✅ Public domains (.com, .io, .app, etc.)"
echo "  ❌ Raw IPs (192.168.x.x)"
echo "  ❌ .local domains"
echo ""
echo "────────────────────────────────────────────────────────────"
echo "STEP 1: Install ngrok"
echo "────────────────────────────────────────────────────────────"
echo ""

if command -v ngrok &> /dev/null; then
    echo "✅ ngrok is already installed"
else
    echo "Installing ngrok..."
    brew install ngrok
fi

echo ""
echo "────────────────────────────────────────────────────────────"
echo "STEP 2: Start ngrok tunnel"
echo "────────────────────────────────────────────────────────────"
echo ""
echo "Run this command in a NEW terminal window:"
echo ""
echo "  ngrok http 3000"
echo ""
echo "You'll see output like:"
echo "  Forwarding  https://abc123.ngrok-free.app -> http://localhost:3000"
echo ""
echo "────────────────────────────────────────────────────────────"
echo "STEP 3: Copy the HTTPS URL"
echo "────────────────────────────────────────────────────────────"
echo ""
echo "Copy the URL that looks like: https://abc123.ngrok-free.app"
echo ""
echo "────────────────────────────────────────────────────────────"
echo "STEP 4: Update .env.local"
echo "────────────────────────────────────────────────────────────"
echo ""
echo "Replace with YOUR ngrok URL:"
echo ""
echo "NEXT_PUBLIC_APP_URL=https://YOUR-URL.ngrok-free.app"
echo "NEXT_PUBLIC_SITE_URL=https://YOUR-URL.ngrok-free.app"
echo ""
echo "────────────────────────────────────────────────────────────"
echo "STEP 5: Update Google OAuth"
echo "────────────────────────────────────────────────────────────"
echo ""
echo "https://console.cloud.google.com/apis/credentials"
echo ""
echo "Authorized JavaScript origins:"
echo "  https://YOUR-URL.ngrok-free.app"
echo ""
echo "Authorized redirect URIs:"
echo "  https://ajljduisjyutbgjeucig.supabase.co/auth/v1/callback"
echo "  https://YOUR-URL.ngrok-free.app/auth/callback"
echo ""
echo "────────────────────────────────────────────────────────────"
echo "STEP 6: Update Supabase"
echo "────────────────────────────────────────────────────────────"
echo ""
echo "https://supabase.com/dashboard/project/ajljduisjyutbgjeucig/auth/url-configuration"
echo ""
echo "Site URL: https://YOUR-URL.ngrok-free.app"
echo "Redirect URLs: https://YOUR-URL.ngrok-free.app/*"
echo ""
echo "────────────────────────────────────────────────────────────"
echo "STEP 7: Restart dev server"
echo "────────────────────────────────────────────────────────────"
echo ""
echo "  npm run dev"
echo ""
echo "────────────────────────────────────────────────────────────"
echo "STEP 8: Test on phone"
echo "────────────────────────────────────────────────────────────"
echo ""
echo "Open the ngrok URL on your phone (doesn't need same WiFi!)"
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""
echo "💡 TIP: Free ngrok URLs change each restart"
echo "   Sign up at ngrok.com for a static subdomain"
echo ""
echo "🔄 To switch back to localhost development:"
echo "   1. Stop ngrok"
echo "   2. Change .env.local back to http://localhost:3000"
echo "   3. Keep both URLs in Google OAuth settings"
echo ""
