#!/bin/bash

# Find Mac hostname for .local domain setup

echo "🔍 Finding your Mac's hostname for mobile testing..."
echo ""

# Get the local hostname
LOCAL_HOSTNAME=$(scutil --get LocalHostName)

if [ -z "$LOCAL_HOSTNAME" ]; then
    echo "❌ Could not find hostname"
    echo ""
    echo "Run this command to set one:"
    echo "  sudo scutil --set LocalHostName YourMacName"
    exit 1
fi

echo "✅ Your Mac's hostname: $LOCAL_HOSTNAME"
echo ""
echo "════════════════════════════════════════════════════════════"
echo "📱 MOBILE TESTING SETUP (Same WiFi)"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "Your app will be accessible at:"
echo "  🌐 http://${LOCAL_HOSTNAME}.local:3000"
echo ""
echo "This URL works on:"
echo "  ✅ Your Mac"
echo "  ✅ Your iPhone/iPad (same WiFi)"
echo "  ✅ Any device on same network"
echo ""
echo "────────────────────────────────────────────────────────────"
echo "STEP 1: Update .env.local"
echo "────────────────────────────────────────────────────────────"
echo ""
echo "Set these values:"
echo ""
echo "NEXT_PUBLIC_APP_URL=http://${LOCAL_HOSTNAME}.local:3000"
echo "NEXT_PUBLIC_SITE_URL=http://${LOCAL_HOSTNAME}.local:3000"
echo ""
echo "────────────────────────────────────────────────────────────"
echo "STEP 2: Update Google OAuth"
echo "────────────────────────────────────────────────────────────"
echo ""
echo "Go to: https://console.cloud.google.com/apis/credentials"
echo ""
echo "Authorized JavaScript origins:"
echo "  http://${LOCAL_HOSTNAME}.local:3000"
echo ""
echo "Authorized redirect URIs:"
echo "  https://ajljduisjyutbgjeucig.supabase.co/auth/v1/callback"
echo "  http://${LOCAL_HOSTNAME}.local:3000/auth/callback"
echo ""
echo "────────────────────────────────────────────────────────────"
echo "STEP 3: Update Supabase Dashboard"
echo "────────────────────────────────────────────────────────────"
echo ""
echo "Go to: https://supabase.com/dashboard/project/ajljduisjyutbgjeucig/auth/url-configuration"
echo ""
echo "Site URL:"
echo "  http://${LOCAL_HOSTNAME}.local:3000"
echo ""
echo "Redirect URLs:"
echo "  http://${LOCAL_HOSTNAME}.local:3000/*"
echo ""
echo "────────────────────────────────────────────────────────────"
echo "STEP 4: Restart Dev Server"
echo "────────────────────────────────────────────────────────────"
echo ""
echo "  npm run dev"
echo ""
echo "────────────────────────────────────────────────────────────"
echo "STEP 5: Test on Mobile"
echo "────────────────────────────────────────────────────────────"
echo ""
echo "On your iPhone/iPad (connected to same WiFi):"
echo "  Open Safari: http://${LOCAL_HOSTNAME}.local:3000"
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""
echo "✨ This avoids the raw IP issue because .local is a valid TLD!"
echo ""
